services:
    db:
        volumes:
            - ${DATADIR}/sql:/var/lib/mysql

    influxdb:
        ports:
            - "127.0.0.1:${INFLUXDB_PORT}:8086"
        volumes:
            - ${DATADIR}/influxdb/data:/var/lib/influxdb2
            - ${DATADIR}/influxdb/config:/etc/influxdb2

    phpmyadmin:
        container_name: cc-phpmyadmin
        image: phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "127.0.0.1:${PHPMYADMIN_PORT}:80"
        restart: always
