services:
    db:
        volumes:
            - ${DATADIR}/sqldata:/var/lib/mysql

    influxdb:
        container_name: cc-influxdb
        image: influxdb
        command: ["--reporting-disabled"]
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: symfony
            DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
            DOCKER_INFLUXDB_INIT_ORG: ClusterCockpit
            DOCKER_INFLUXDB_INIT_BUCKET: ClusterCockpit
            DOCKER_INFLUXDB_INIT_RETENTION: 2y
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
        ports:
            - "127.0.0.1:${INFLUXDB_PORT}:8086"
        volumes:
            - ${DATADIR}/influxdb/data:/var/lib/influxdb2
            - ${DATADIR}/influxdb/config:/etc/influxdb2

    phpmyadmin:
        container_name: cc-phpmyadmin
        image: phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "127.0.0.1:${PHPMYADMIN_PORT}:80"
        restart: always
