services:
  nats:
    container_name: nats
    image: nats:alpine
    ports:
      - "4222:4222"
      - "8222:8222"

  db:
    container_name: cc-db
    image: mysql:8.0.22
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DATADIR}/sql-init:/docker-entrypoint-initdb.d
      # - ${DATADIR}/sqldata:/var/lib/mysql
    cap_add:
      - SYS_NICE

  influxdb:
    container_name: cc-influxdb
    image: influxdb
    command: ["--reporting-disabled"]
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: symfony
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_RETENTION: 100w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    ports:
      - "127.0.0.1:${INFLUXDB_PORT}:8086"
    volumes:
      - ${DATADIR}/influxdb/data:/var/lib/influxdb2
      - ${DATADIR}/influxdb/config:/etc/influxdb2

  cc-metric-store:
    container_name: metric-store
    build:
      context: ./cc-metric-store
    depends_on:
      - nats

  openldap:
    container_name: cc-ldap
    image: osixia/openldap:1.5.0
    command: --copy-service --loglevel debug
    environment:
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
    volumes:
      - ${DATADIR}/ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom

  redis:
    container_name: cc-redis
    image: redis
    command: [
      "redis-server",
      "--save",             "",
      "--maxmemory",        "2gb",
      "--maxmemory-policy", "allkeys-lru"]

  php:
    container_name: cc-php
    build:
      context: ./php-fpm
      args:
        PHP_XDEBUG_INIT: ${PHP_XDEBUG_INIT}
        PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
        PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
        PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
        SYMFONY_CLI_VERSION: 4.23.2
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        LDAP_PASSWORD: ${LDAP_ADMIN_PASSWORD}
        INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
        INFLUXDB_PORT: ${INFLUXDB_PORT}
        INFLUXDB_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
        INFLUXDB_ORG: ${INFLUXDB_ORG}
        INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
        INFLUXDB_SSL: ${INFLUXDB_SSL}
        APP_ENVIRONMENT: ${APP_ENVIRONMENT}
    environment:
      - APP_CLUSTERCOCKPIT_INIT=${APP_CLUSTERCOCKPIT_INIT}
      - CLUSTERCOCKPIT_BRANCH=${CLUSTERCOCKPIT_BRANCH}
      - APP_JWT_PUB_KEY=${APP_JWT_PUB_KEY}
      - APP_JWT_PRIV_KEY=${APP_JWT_PRIV_KEY}
    volumes:
      - ${DATADIR}/symfony:/var/www/symfony:cached
      - ${DATADIR}/job-archive:/var/lib/job-archive:cached
    depends_on:
      - db
      - redis
      - influxdb

  nginx:
    container_name: cc-nginx
    build:
      context: ./nginx
    ports:
      - "127.0.0.1:${NGINX_PORT}:80"
    depends_on:
      - php
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
    volumes:
      - ${DATADIR}/symfony:/var/www/symfony:cached

  phpmyadmin:
    container_name: cc-phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_HOST=cc-db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:${PHPMYADMIN_PORT}:80"
